void wspaceread()
{
  // R e a d   w o r k s p a c e   f r o m   f i l e
  // -----------------------------------------------

  // Open input file with workspace (generated by rf14_wspacewrite)
  //TFile *f = new TFile("root://eoscms.cern.ch//eos/cms/store/group/phys_higgs/cmshgg/analyzed/ichep2016/flashgg-workspaces//allData.root") ;

  //TFile *f = new TFile("/afs/cern.ch/user/f/ftorresd/workSpace/public/paraElizaESandro/fitPlotFiles/HToJPsiPhotonSignalAndBackgroundFit/HToJPsiPhotonSignalAndBackgroundFit_workspace_forFLASHGG_Cat0.root") ;

   //TFile *f = new TFile("HToJPsiPhotonSignalAndBackgroundFit_workspace_Cat0.root") ;

//  /afs/cern.ch/user/f/ftorresd/workSpace/public/paraSandro/fitPlotFiles/HToUpsilonPhotonSignalAndBackgroundFit/
  //TFile *f = new TFile("HToJPsiPhotonSignalAndBackgroundFit_workspace.root");
 // TFile *f = new TFile("HToJPsiPhotonSignalAndBackgroundFit_workspace_Cat0.root");
   TFile *f = new TFile("roostats-7MsQ5Z.root");
  // Retrieve workspace from file
    RooWorkspace* w = (RooWorkspace*) f->Get("w") ;
  //RooWorkspace* w = (RooWorkspace*) f->Get("tagsDumper/cms_hgg_13TeV") ;
   //RooWorkspace* w = (RooWorkspace*) f->Get("backgrounds") ;
  w->Print();
/*
	RooDataSet *dataFull;
        dataFull = (RooDataSet*)w->data(Form("Data_13TeV_UntaggedTag_0"));
        cout << "Entries: " <<dataFull->sumEntries() << endl;
       cout << "weight: " << dataFull->weight() << endl;
//        cout << dataFull->mass() << endl;

// get variable x (is the first of the data)
   RooRealVar * x = w->var("CMS_hgg_mass"); 
   RooPlot * plot = x->frame();

   dataFull->plotOn(plot);
   plot->Draw();

*/
}
