#include <iostream>
#include <fstream>
#include <string>
#include <iomanip>

using namespace std; 

void wspaceread()
{

ofstream dataF;
dataF.open("mass.txt",ios::app|ios::ate);


  // R e a d   w o r k s p a c e   f r o m   f i l e
  // -----------------------------------------------

  // Open input file with workspace (generated by rf14_wspacewrite)
  //TFile *f = new TFile("root://eoscms.cern.ch//eos/cms/store/group/phys_higgs/cmshgg/analyzed/ichep2016/flashgg-workspaces//allData.root") ;

 // TFile *f = new TFile("/afs/cern.ch/user/f/ftorresd/workSpace/public/paraSandro/fitPlotFiles/HToJPsiPhotonSignalAndBackgroundFit/HToJPsiPhotonSignalAndBackgroundFit_workspace_forFLASHGG.root") ;

//  /afs/cern.ch/user/f/ftorresd/workSpace/public/paraSandro/fitPlotFiles/HToUpsilonPhotonSignalAndBackgroundFit/
TFile *f = new TFile("CMS-HGG_multipdf_HToJPsiGamma_afterFtest.root");

  // Retrieve workspace from file
  RooWorkspace* w = (RooWorkspace*) f->Get("multipdf") ;

  w->Print();
/*	RooDataSet *dataFull;
        dataFull = (RooDataSet*)w->data(Form("Data_13TeV_UntaggedTag_0"));
        cout << "Entries: " <<dataFull->sumEntries() << endl;
        cout << "weight: " << dataFull->weight() << endl;
//        cout << dataFull->mass() << endl;
  // stringstream var_cache;
// get variable x (is the first of the data)
   RooRealVar * x = w->var("CMS_hgg_mass"); 
   RooPlot * plot = x->frame();
   RooArgSet* event;   

 for (int i = 0 ; i <dataFull->sumEntries()  ; i++) {
 dataFull->get(i)->Print("v");
// event->dataFull.get(i) ;

 //x->get(i)->printValue(cout);
}
//dataFull->Print(" ");


  cout<<endl;
  w->allVars().writeToFile("test.txt");
    
   dataFull->plotOn(plot);
   plot->Draw();

*/
}
